# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nww3Wrf',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('lon', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('dir', models.FloatField()),
                ('hs', models.FloatField()),
                ('fd', models.FloatField()),
                ('fhs', models.FloatField()),
            ],
            options={
                'db_table': 'NWW3_WRF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObserveDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.CharField(db_column='StationID', max_length=6)),
                ('observetime', models.DateTimeField(db_column='ObserveTime')),
                ('winddir16', models.CharField(db_column='WindDir16', max_length=16)),
                ('wind', models.DecimalField(db_column='Wind', decimal_places=2, max_digits=5)),
                ('gust', models.DecimalField(db_column='Gust', decimal_places=2, max_digits=5)),
                ('windscale', models.SmallIntegerField(db_column='WindScale')),
                ('gustscale', models.SmallIntegerField(db_column='GustScale')),
                ('visibility', models.DecimalField(db_column='Visibility', decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(db_column='Temperature', decimal_places=2, max_digits=5)),
                ('humidity', models.SmallIntegerField(db_column='Humidity')),
                ('pressure', models.DecimalField(db_column='Pressure', decimal_places=2, max_digits=6)),
                ('sunshine', models.DecimalField(blank=True, db_column='Sunshine', decimal_places=1, max_digits=5, null=True)),
                ('weather_zhtw', models.CharField(db_column='Weather_zhtw', max_length=20)),
                ('updatetime', models.DateTimeField(db_column='UpdateTime')),
            ],
            options={
                'db_table': 'observe_datum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocm3',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('depth', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=10)),
                ('temp', models.FloatField()),
                ('speed', models.FloatField()),
                ('dir', models.FloatField()),
            ],
            options={
                'db_table': 'OCM3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='STwarn',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('warning', models.CharField(max_length=100)),
                ('max_fhs', models.FloatField()),
            ],
            options={
                'db_table': 'STWarn',
                'managed': False,
            },
        ),
    ]
