# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('project', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'manage_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDatasetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'manage_application_dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.CharField(max_length=10)),
                ('county_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'info_county',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('latlng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'info_datapoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatapointStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=16, unique=True)),
                ('related_name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'info_datapoint_strategy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=16, unique=True)),
                ('category', models.CharField(max_length=16)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'info_dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('group_name', models.CharField(blank=True, max_length=16, null=True)),
                ('location_name', models.CharField(blank=True, max_length=16, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manage_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('latlng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manage_view_point',
                'managed': False,
            },
        ),
    ]
