"""
Django settings for webapi project.

Generated by 'django-admin startproject' using Django 1.11.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import socket

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b5khz(qs+e*dm^beyeaz0(rzmsl)t@w&0*vr%w_&exqcao%1cr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if 'cwspap' in socket.gethostname() else True

ALLOWED_HOSTS = ['cwspapsvr.cwb.gov.tw', 'cwspapsvr1.cwb.gov.tw', 'cwspapsvr2.cwb.gov.tw', '10.6.1.13', 'localhost', '127.0.0.1', '61.60.103.175']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.gis',
    'rest_framework',
    'rest_framework_swagger',
    'django_filters',
    'rest_framework_filters',
    'crispy_forms',
    'corsheaders',
    'Manage',
    'DataStore',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'webapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASE_ROUTERS = [
    'qiange.dbrouters.CRSdbRouter',
    # 'qiange.dbrouters.MetaDBRouter',
]


ENGINE = 'django.db.backends.mysql'
CRS_DB_HOST = '61.60.103.175'
# LOCALHOST = 'localhost'
LOCALHOST = '61.60.103.175'
USERNAME = 'crsopr'
# USERNAME = 'root'

PASSWORD = 'cwb+123'
# PASSWORD = ''

DATABASES = {
    'default': {
        'ENGINE': ENGINE,
        'NAME': 'django',
        'USER': USERNAME,
        'PASSWORD': PASSWORD,
        'HOST': LOCALHOST,
        'PORT': 3306,
        'TEST_CHARSET': "utf8",
        'TEST_COLLATION': "utf8_general_ci",
    },
    'CRSdb': {
        'ENGINE': ENGINE,
        'NAME': 'CRSdb',
        'USER': USERNAME,
        'PASSWORD': PASSWORD,
        'HOST': CRS_DB_HOST,
        'PORT': 3306,
        'TEST_CHARSET': "utf8",
        'TEST_COLLATION': "utf8_general_ci",
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


LOGIN_URL = '/api/v1/accounts/login'
LOGOUT_URL = '/api/v1/accounts/logout'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_filters.backends.DjangoFilterBackend',
    ),
    'PAGE_SIZE': 10,
}

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static"),
]

#########################
# django-cors-headers
#########################

CORS_ORIGIN_ALLOW_ALL = True

# from cors
#
# headers.defaults import default_headers
# CORS_ALLOW_HEADERS = default_headers + ('at', )

#########################
#  rest_framework_jwt
#########################
import datetime

JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=60 * 60 * 24),
}
